### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by shenzt** [sinchang/miaopai-downloader#1]
/usr/lib/node_modules/miaopai-downloader/src/index.js:14
    (async function () {
           ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/miaopai-downloader/cli.js:4:20)

**Comment by sinchang** [comment]
what's your Node version?

**Comment by sinchang** [comment]
need >=v8.9.0
